#!name=Radio Javan Premium
#!desc= Remove ads and high quality music in radio javan

[MITM]
hostname = %APPEND% cloudrj-api.com

[Script]
rj_request = type=http-request,pattern=^https:\/\/cloudrj-app\.com\/api2\/?,requires-body=1,binary-body-mode=0,script-path=https://raw.githubusercontent.com/ErfanM98/Shadowrocket-ad_block-rules/main/radiojavan/rj_req.js
rj_response = type=http-response,pattern=^https:\/\/cloudrj-app\.com\/api2\/?,requires-body=1,binary-body-mode=0,script-path=https://raw.githubusercontent.com/ErfanM98/Shadowrocket-ad_block-rules/main/radiojavan/radiojavan_pro.js
